### ISSUE TITLE
`oci_exec_test` should support a timeout

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/terraform-provider-oci#39]
Maybe this can be done at the TF level too, but it'd be great to be able to specify at the `oci` provider level too (e.g. tests in this apply should have a default timeout of `30s`).

cc @imjasonh

**Comment by imjasonh** [comment]
> [timeout_seconds](https://registry.terraform.io/providers/chainguard-dev/oci/latest/docs/data-sources/exec_test#timeout_seconds) (Number) Timeout for the test in seconds (default is 5 minutes)

**Comment by mattmoor** [comment]
🤯 awesome, let's use this for a provider-level default?
